apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkedin-post-generator
  namespace: linkedin-post-generator
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: linkedin-post-generator.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80